"""initial schema

Revision ID: b7e80ff751a5
Revises: 
Create Date: 2026-06-18 21:33:36.408731
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7e80ff751a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_table(name: str, *elements: object) -> None:
    if op.get_bind().dialect.name == "mssql":
        for element in elements:
            if isinstance(element, sa.ForeignKeyConstraint):
                element.ondelete = None
    op.create_table(name, *elements)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_subject', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_subject'), 'audit_logs', ['actor_subject'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_team_id'), 'audit_logs', ['team_id'], unique=False)
    _create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    _create_table('outbox_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_organization_id'), 'outbox_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_published_at'), 'outbox_events', ['published_at'], unique=False)
    _create_table('capacity_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.Column('daily_focus_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ceremony_hours_per_sprint', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('meeting_buffer_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('support_buffer_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('review_buffer_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unplanned_buffer_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_capacity_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_profiles')),
    sa.UniqueConstraint('organization_id', 'role_name', name=op.f('uq_capacity_profiles_organization_id'))
    )
    op.create_index(op.f('ix_capacity_profiles_organization_id'), 'capacity_profiles', ['organization_id'], unique=False)
    _create_table('dashboard_read_models',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dashboard_read_models_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_read_models')),
    sa.UniqueConstraint('organization_id', 'resource_type', 'resource_id', 'sprint_id', name=op.f('uq_dashboard_read_models_organization_id'))
    )
    op.create_index(op.f('ix_dashboard_read_models_organization_id'), 'dashboard_read_models', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dashboard_read_models_resource_id'), 'dashboard_read_models', ['resource_id'], unique=False)
    op.create_index(op.f('ix_dashboard_read_models_sprint_id'), 'dashboard_read_models', ['sprint_id'], unique=False)
    _create_table('employees',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('payspace_employee_number', sa.String(length=100), nullable=True),
    sa.Column('jira_account_id', sa.String(length=255), nullable=True),
    sa.Column('corporate_email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('manager_employee_id', sa.Uuid(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('location_code', sa.String(length=32), nullable=True),
    sa.Column('contract_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fte_factor', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], name=op.f('fk_employees_manager_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employees_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('organization_id', 'corporate_email', name=op.f('uq_employees_organization_id'))
    )
    op.create_index(op.f('ix_employees_active'), 'employees', ['active'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_jira_account_id'), 'employees', ['jira_account_id'], unique=False)
    op.create_index(op.f('ix_employees_location_code'), 'employees', ['location_code'], unique=False)
    op.create_index(op.f('ix_employees_manager_employee_id'), 'employees', ['manager_employee_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_payspace_employee_number'), 'employees', ['payspace_employee_number'], unique=False)
    op.create_index(op.f('ix_employees_role_name'), 'employees', ['role_name'], unique=False)
    _create_table('integration_configurations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('JIRA', 'PAYSPACE', name='integrationsource', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('secret_reference', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_configurations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_configurations')),
    sa.UniqueConstraint('organization_id', 'source', 'name', name=op.f('uq_integration_configurations_organization_id'))
    )
    op.create_index(op.f('ix_integration_configurations_organization_id'), 'integration_configurations', ['organization_id'], unique=False)
    _create_table('integration_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('JIRA', 'PAYSPACE', name='integrationsource', native_enum=False, length=20), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='integrationrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('cursor', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_runs'))
    )
    op.create_index(op.f('ix_integration_runs_organization_id'), 'integration_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integration_runs_source'), 'integration_runs', ['source'], unique=False)
    op.create_index(op.f('ix_integration_runs_status'), 'integration_runs', ['status'], unique=False)
    _create_table('jira_field_mappings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('jira_site_id', sa.String(length=100), nullable=False),
    sa.Column('logical_field', sa.String(length=100), nullable=False),
    sa.Column('jira_field_id', sa.String(length=100), nullable=False),
    sa.Column('transformation', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jira_field_mappings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_field_mappings')),
    sa.UniqueConstraint('organization_id', 'jira_site_id', 'logical_field', name=op.f('uq_jira_field_mappings_organization_id'))
    )
    op.create_index(op.f('ix_jira_field_mappings_organization_id'), 'jira_field_mappings', ['organization_id'], unique=False)
    _create_table('public_holidays',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('location_code', sa.String(length=32), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_public_holidays_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_holidays')),
    sa.UniqueConstraint('organization_id', 'location_code', 'holiday_date', name=op.f('uq_public_holidays_organization_id'))
    )
    op.create_index(op.f('ix_public_holidays_holiday_date'), 'public_holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_public_holidays_organization_id'), 'public_holidays', ['organization_id'], unique=False)
    _create_table('teams',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('location_code', sa.String(length=32), nullable=True),
    sa.Column('velocity_lookback', sa.Integer(), nullable=False),
    sa.Column('working_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_teams_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_teams_organization_id'))
    )
    op.create_index(op.f('ix_teams_active'), 'teams', ['active'], unique=False)
    op.create_index(op.f('ix_teams_department'), 'teams', ['department'], unique=False)
    op.create_index(op.f('ix_teams_location_code'), 'teams', ['location_code'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    _create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_organization_id_email'),
    sa.UniqueConstraint('organization_id', 'external_subject', name='uq_users_organization_id_external_subject')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    _create_table('webhook_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('JIRA', 'PAYSPACE', name='integrationsource', native_enum=False, length=20), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_webhook_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('organization_id', 'source', 'external_event_id', name=op.f('uq_webhook_events_organization_id'))
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed_at'), 'webhook_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_source'), 'webhook_events', ['source'], unique=False)
    _create_table('identity_mappings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('jira_account_id', sa.String(length=255), nullable=True),
    sa.Column('payspace_employee_number', sa.String(length=100), nullable=True),
    sa.Column('corporate_email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_identity_mappings_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_identity_mappings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_identity_mappings_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_mappings'))
    )
    op.create_index(op.f('ix_identity_mappings_corporate_email'), 'identity_mappings', ['corporate_email'], unique=False)
    op.create_index(op.f('ix_identity_mappings_employee_id'), 'identity_mappings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_identity_mappings_jira_account_id'), 'identity_mappings', ['jira_account_id'], unique=False)
    op.create_index(op.f('ix_identity_mappings_organization_id'), 'identity_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_identity_mappings_payspace_employee_number'), 'identity_mappings', ['payspace_employee_number'], unique=False)
    op.create_index(op.f('ix_identity_mappings_status'), 'identity_mappings', ['status'], unique=False)
    _create_table('leave_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('partial_day_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_reference_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_records_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_records')),
    sa.UniqueConstraint('employee_id', 'source_reference_id', name=op.f('uq_leave_records_employee_id'))
    )
    op.create_index('ix_leave_employee_dates', 'leave_records', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_leave_records_employee_id'), 'leave_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_records_status'), 'leave_records', ['status'], unique=False)
    _create_table('risk_thresholds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('risk_type', sa.String(length=80), nullable=False),
    sa.Column('warning_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('critical_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_thresholds_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_risk_thresholds_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_thresholds'))
    )
    op.create_index(op.f('ix_risk_thresholds_organization_id'), 'risk_thresholds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_thresholds_team_id'), 'risk_thresholds', ['team_id'], unique=False)
    _create_table('sprints',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('jira_sprint_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('FUTURE', 'ACTIVE', 'CLOSED', name='sprintstate', native_enum=False, length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_sprints_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints')),
    sa.UniqueConstraint('team_id', 'jira_sprint_id', name=op.f('uq_sprints_team_id'))
    )
    op.create_index(op.f('ix_sprints_jira_sprint_id'), 'sprints', ['jira_sprint_id'], unique=False)
    op.create_index(op.f('ix_sprints_state'), 'sprints', ['state'], unique=False)
    op.create_index(op.f('ix_sprints_team_id'), 'sprints', ['team_id'], unique=False)
    _create_table('team_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_access_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_access')),
    sa.UniqueConstraint('user_id', 'team_id', name=op.f('uq_team_access_user_id'))
    )
    op.create_index(op.f('ix_team_access_team_id'), 'team_access', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_access_user_id'), 'team_access', ['user_id'], unique=False)
    _create_table('team_memberships',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delivery_role', sa.String(length=120), nullable=True),
    sa.Column('critical_role', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_team_memberships_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_memberships_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_memberships'))
    )
    op.create_index('ix_team_membership_effective', 'team_memberships', ['team_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_team_memberships_delivery_role'), 'team_memberships', ['delivery_role'], unique=False)
    op.create_index(op.f('ix_team_memberships_employee_id'), 'team_memberships', ['employee_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    _create_table('employee_capacity_snapshots',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('working_days', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('gross_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('leave_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ceremony_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buffer_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_person_days', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('assigned_story_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_capacity_snapshots_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_employee_capacity_snapshots_sprint_id_sprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_capacity_snapshots')),
    sa.UniqueConstraint('sprint_id', 'employee_id', name=op.f('uq_employee_capacity_snapshots_sprint_id'))
    )
    op.create_index(op.f('ix_employee_capacity_snapshots_employee_id'), 'employee_capacity_snapshots', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_capacity_snapshots_sprint_id'), 'employee_capacity_snapshots', ['sprint_id'], unique=False)
    _create_table('jira_issues',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('jira_site_id', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('issue_key', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('assignee_employee_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('status_category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('issue_type', sa.String(length=80), nullable=True),
    sa.Column('epic_key', sa.String(length=50), nullable=True),
    sa.Column('story_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('added_to_sprint_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_from_sprint_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_fields', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_employee_id'], ['employees.id'], name=op.f('fk_jira_issues_assignee_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jira_issues_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_jira_issues_sprint_id_sprints'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jira_issues')),
    sa.UniqueConstraint('organization_id', 'jira_site_id', 'external_id', name=op.f('uq_jira_issues_organization_id'))
    )
    op.create_index(op.f('ix_jira_issues_assignee_employee_id'), 'jira_issues', ['assignee_employee_id'], unique=False)
    op.create_index(op.f('ix_jira_issues_blocked'), 'jira_issues', ['blocked'], unique=False)
    op.create_index(op.f('ix_jira_issues_epic_key'), 'jira_issues', ['epic_key'], unique=False)
    op.create_index(op.f('ix_jira_issues_issue_key'), 'jira_issues', ['issue_key'], unique=False)
    op.create_index(op.f('ix_jira_issues_issue_type'), 'jira_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_jira_issues_organization_id'), 'jira_issues', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jira_issues_priority'), 'jira_issues', ['priority'], unique=False)
    op.create_index(op.f('ix_jira_issues_sprint_id'), 'jira_issues', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_jira_issues_status'), 'jira_issues', ['status'], unique=False)
    op.create_index(op.f('ix_jira_issues_status_category'), 'jira_issues', ['status_category'], unique=False)
    _create_table('risk_signals',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('risk_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskseverity', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_risk_signals_acknowledged_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_signals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_risk_signals_sprint_id_sprints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_risk_signals_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_signals'))
    )
    op.create_index(op.f('ix_risk_signals_fingerprint'), 'risk_signals', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_risk_signals_organization_id'), 'risk_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_resolved_at'), 'risk_signals', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_risk_type'), 'risk_signals', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_sprint_id'), 'risk_signals', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_team_id'), 'risk_signals', ['team_id'], unique=False)
    _create_table('sprint_commitment_snapshots',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('START', 'DAILY', 'COMPLETE', 'MANUAL', 'SCOPE_CHANGED', 'LEAVE_CHANGED', name='snapshottype', native_enum=False, length=30), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_ids', sa.JSON(), nullable=False),
    sa.Column('committed_story_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_story_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('removed_story_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('completed_story_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_sprint_commitment_snapshots_sprint_id_sprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprint_commitment_snapshots'))
    )
    op.create_index(op.f('ix_sprint_commitment_snapshots_captured_at'), 'sprint_commitment_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_sprint_commitment_snapshots_sprint_id'), 'sprint_commitment_snapshots', ['sprint_id'], unique=False)
    _create_table('team_capacity_summaries',
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_person_days', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('leave_impact_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('story_points_per_effective_day', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('story_point_capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('committed_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('added_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('removed_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('completed_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('in_progress_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('utilization_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('inputs_fresh_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_team_capacity_summaries_sprint_id_sprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_capacity_summaries')),
    sa.UniqueConstraint('sprint_id', name=op.f('uq_team_capacity_summaries_sprint_id'))
    )
    _create_table('team_velocity_metrics',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('completed_story_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_person_days', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('story_points_per_effective_day', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_team_velocity_metrics_sprint_id_sprints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_velocity_metrics_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_velocity_metrics')),
    sa.UniqueConstraint('sprint_id', name=op.f('uq_team_velocity_metrics_sprint_id'))
    )
    op.create_index(op.f('ix_team_velocity_metrics_team_id'), 'team_velocity_metrics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_velocity_metrics_team_id'), table_name='team_velocity_metrics')
    op.drop_table('team_velocity_metrics')
    op.drop_table('team_capacity_summaries')
    op.drop_index(op.f('ix_sprint_commitment_snapshots_sprint_id'), table_name='sprint_commitment_snapshots')
    op.drop_index(op.f('ix_sprint_commitment_snapshots_captured_at'), table_name='sprint_commitment_snapshots')
    op.drop_table('sprint_commitment_snapshots')
    op.drop_index(op.f('ix_risk_signals_team_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_sprint_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_risk_type'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_resolved_at'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_organization_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_fingerprint'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_jira_issues_status_category'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_status'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_sprint_id'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_priority'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_organization_id'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_issue_type'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_issue_key'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_epic_key'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_blocked'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_assignee_employee_id'), table_name='jira_issues')
    op.drop_table('jira_issues')
    op.drop_index(op.f('ix_employee_capacity_snapshots_sprint_id'), table_name='employee_capacity_snapshots')
    op.drop_index(op.f('ix_employee_capacity_snapshots_employee_id'), table_name='employee_capacity_snapshots')
    op.drop_table('employee_capacity_snapshots')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_employee_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_delivery_role'), table_name='team_memberships')
    op.drop_index('ix_team_membership_effective', table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_team_access_user_id'), table_name='team_access')
    op.drop_index(op.f('ix_team_access_team_id'), table_name='team_access')
    op.drop_table('team_access')
    op.drop_index(op.f('ix_sprints_team_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_state'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_jira_sprint_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_risk_thresholds_team_id'), table_name='risk_thresholds')
    op.drop_index(op.f('ix_risk_thresholds_organization_id'), table_name='risk_thresholds')
    op.drop_table('risk_thresholds')
    op.drop_index(op.f('ix_leave_records_status'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_employee_id'), table_name='leave_records')
    op.drop_index('ix_leave_employee_dates', table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_identity_mappings_status'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_payspace_employee_number'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_organization_id'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_jira_account_id'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_employee_id'), table_name='identity_mappings')
    op.drop_index(op.f('ix_identity_mappings_corporate_email'), table_name='identity_mappings')
    op.drop_table('identity_mappings')
    op.drop_index(op.f('ix_webhook_events_source'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_location_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_department'), table_name='teams')
    op.drop_index(op.f('ix_teams_active'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_public_holidays_organization_id'), table_name='public_holidays')
    op.drop_index(op.f('ix_public_holidays_holiday_date'), table_name='public_holidays')
    op.drop_table('public_holidays')
    op.drop_index(op.f('ix_jira_field_mappings_organization_id'), table_name='jira_field_mappings')
    op.drop_table('jira_field_mappings')
    op.drop_index(op.f('ix_integration_runs_status'), table_name='integration_runs')
    op.drop_index(op.f('ix_integration_runs_source'), table_name='integration_runs')
    op.drop_index(op.f('ix_integration_runs_organization_id'), table_name='integration_runs')
    op.drop_table('integration_runs')
    op.drop_index(op.f('ix_integration_configurations_organization_id'), table_name='integration_configurations')
    op.drop_table('integration_configurations')
    op.drop_index(op.f('ix_employees_role_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_payspace_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_location_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_jira_account_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_active'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_dashboard_read_models_sprint_id'), table_name='dashboard_read_models')
    op.drop_index(op.f('ix_dashboard_read_models_resource_id'), table_name='dashboard_read_models')
    op.drop_index(op.f('ix_dashboard_read_models_organization_id'), table_name='dashboard_read_models')
    op.drop_table('dashboard_read_models')
    op.drop_index(op.f('ix_capacity_profiles_organization_id'), table_name='capacity_profiles')
    op.drop_table('capacity_profiles')
    op.drop_index(op.f('ix_outbox_events_published_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_organization_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_team_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_subject'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
